# Generated by Django 4.1.3 on 2022-11-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("date_of_creation", models.DateTimeField(auto_now=True)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("done", models.BooleanField()),
                ("teg", models.ManyToManyField(related_name="tasks", to="task.teg")),
            ],
        ),
    ]
