# Generated by Django 4.1.3 on 2022-12-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_alter_task_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="tags",
        ),
        migrations.AddField(
            model_name="task",
            name="tag",
            field=models.ManyToManyField(related_name="tasks", to="task.tag"),
        ),
    ]
